data:
  nuscenes:
    n_pillars_x: 640
    n_pillars_y: 640
    point_features: 6 # maximum 7
    x_min: -35
    x_max: 35
    y_min: -35
    y_max: 35
    z_min: 0.5
    z_max: 10
    batch_size: 1
    has_test: True
    num_workers: 4
    n_points: 8192
    apply_pillarization: True
    shuffle_train: True